version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:example@mongo:27017/formotex?authSource=admin
      - JWT_SECRET=tu_clave_secreta
      - JWT_EXPIRES_IN=1d
      - ADMIN_EMAIL=admin@admin.com
      - ADMIN_PASSWORD=admin123
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev # para desarrollo, cambia a npm run start para producción

volumes:
  mongo-data:
